### ISSUE TITLE
Dragging the color picker causes everything to freeze

### ISSUE THREAD

**Issue by DevoliaEsp** [ljmerza/light-entity-card#107]
Since the latest release, I can't control my group lights by dragging the color picker to the desired colored.
If I drag it, my lightbulbs will freeze, and everything becomes unresponsive, even other lightbulbs, not in the group, won't respond for a period of time, I can't turn them off, or change their colors.
The problem doesn't seems to affect as much individual lights, which can't be controled by dragging the color picker either, but at least for them, it doesn't freeze all light control for a solid minute.

If I just click on the color I want on the color wheel, there is no problem whatsoever, it's just a problem when dragging the color picker, which is almost a necessity on my tablet to achieve the exact color I want.

**Comment by conorlap** [comment]
I've created a helper light group for the light groups I want to use this card with. It seems to work better than using the native Philips Hue integration groups. 

How to create the light group:
Integrations > Helpers > + Create Helper > Group > Light Group

**Comment by BobbieERay** [comment]
I have the same issue, when using the color wheel with a Pihlips Hue light. As soon as I pick a color, the card becomes unresponsive and cycles through the colors randomly. The only chance to get HA to respond, is to restart Home Assistant. Same behaviour on Windows -> Edge and iOS -> HA app

![Minimalist_Color_Wheel_Freezes](https://github.com/ljmerza/light-entity-card/assets/7354828/206380aa-7b9a-4607-959a-0dad1f671b57)

**Comment by robinfru** [comment]
+1

**Comment by SuperSandro2000** [comment]
> I've created a helper light group for the light groups I want to use this card with.

That also helped in my case with govee. My theory is that this delays the updates being send to the device which is also done for the default widget.

**Comment by ljmerza** [comment]
should be fixed in v6.1.1
