### ISSUE TITLE
Feature Request - Full row slider

### ISSUE THREAD

**Issue by leloberg** [ljmerza/light-entity-card#11]
Hi

Would it be possible to add a full row solution, so that the slider will be the full width of the card that it resides in? This is a possibility in Thomas Loven's slider-entity-row (see Full Row). 
https://github.com/thomasloven/lovelace-slider-entity-row

See attached screenshot below, where one is with your slider, and the other with slider-entity-row

![Screenshot_1](https://user-images.githubusercontent.com/8376070/54517695-aecffe00-4962-11e9-8ac2-52f09c05438f.png)

**Comment by ljmerza** [comment]
added in v2.5.0
