### ISSUE TITLE
Feature (re)request: bring back the not smooth color wheel

### ISSUE THREAD

**Issue by EmielRous** [ljmerza/light-entity-card#110]
In version 6 the smooth color wheel option was removed. I liked that better than the smooth wheel, because I change between a few colors and I can remember more easily which color I used. Now I have to readjust it every time because I can never remember exaclty where on the wheel the my preferred colors are.

**Comment by GunterAv** [comment]
... and it is much easier to adjust the color

**Comment by ljmerza** [comment]
should be fixed in v6.1.1
