### ISSUE TITLE
Color picker (wheel) keeps changing colors

### ISSUE THREAD

**Issue by turkomano** [ljmerza/light-entity-card#113]
I've been facing a persistent issue with the color picker tool, which is affecting its usability. Initially, I can select a color without any problems. However, after the first selection, the tool appears to continuously track the mouse cursor's position to change the color. This results in constant color changes as long as the cursor is moving. The color selection only stabilizes when the cursor is stationary or if I switch to a different application.

**Comment by ljmerza** [comment]
should be fixed in v6.1.1

**Comment by turkomano** [comment]
Now it appears that I have a different problem. I cannot change the color at all. After selecting a color it snaps back to its original color, making no change to the state of the color.
