### ISSUE TITLE
cannot remove card

### ISSUE THREAD

**Issue by collateral87** [ljmerza/light-entity-card#115]
Hey guys, I need some support. A long time ago, I installed this card and now I have uninstalled it via HACS. However, when I edit a dashboard afterward, I can still select the card from the list of cards.
It must still exist somewhere..

What I've tried so far:
 - uninstalling
 - inspecting the www/community folder
 - deleting it from resources
 - restart ha
 - reinstalling and uninstalling
 - searching in config folder

**Comment by ljmerza** [comment]
you'll probably get better support here https://community.home-assistant.io/t/light-entity-card/96146
