### ISSUE TITLE
Version 6.1.0 works but 6.1.1 fails to load

### ISSUE THREAD

**Issue by DrJohnT** [ljmerza/light-entity-card#116]
After upgrading (via HACS) from 6.1.0 to 6.1.1 my system no longer can locate the light-entity-card

I reverted to 6.1.0 using HACS and everything great again.

**Comment by haplm** [comment]
The same here

**Comment by msl2424** [comment]
I have the same issue.

**Comment by budswarez** [comment]
I have the same problem, I had to go back to the previous version.

**Comment by antro31** [comment]
Same here

**Comment by wokkeltje13** [comment]
same issue

**Comment by Psytoshgen** [comment]
Hi!
May be trouble in card id? 
ive got this js module after installation
/hacsfiles/light-entity-card/null?hacstag=168744428611

**Comment by MobilityManager** [comment]
Same issue here. How can you downgrade to 6.1.0 with HACS? Can someone please explain?

**Comment by ljmerza** [comment]
sorry for the late response updated to fix this

**Comment by cyablo** [comment]
Doesn't seem to be fixed for latest 2024.1.0 non-beta HA Core.

**Comment by iks82** [comment]
For me, the update to v6.1.2 (from v6.1.1 I think) did not workas well.
But remove and re-install did the trick.

**Comment by cyablo** [comment]
Remove -> re-install 6.1.2 on 2024.1.0 does not work for me. Still fails to load.

**Comment by jsiemek** [comment]
Double-check what is in your resources. It should be:

/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428612

NOT:

/hacsfiles/light-entity-card/null?hacstag=168744428612

**Comment by antro31** [comment]
@jsiemek : Yes, that makes it work!

For other: Resources are available on clicking the "three dots" button at the top right corner in the "dashboard" setting menu.

**Comment by cyablo** [comment]
@jsiemek : Now it works.

**Comment by antro31** [comment]
There is certainly something wrong with it's installation.

**Comment by zSprawl** [comment]
> @jsiemek : Now it works.
> 
> But now HACS complains about 1 lovelace element that could not be loaded. Looks like this is only a workaround.

Instead of editing the bad one with null, I added another entry with the correct path so there are two entries now. This allows it to work and not display the Lovelace error.

**Comment by antro31** [comment]
@zSprawl : Nice trick !. 
Still hopping that @ljmerza is able to correct the installation.

**Comment by ljmerza** [comment]
Sorry not sure what's wrong with the installation?

**Comment by jsiemek** [comment]
Hacks during install add wrong entry into resources:

**Comment by antro31** [comment]
When installing, this adds `/hacsfiles/light-entity-card/null?hacstag=168744428612` as a resource whereas it should add `'/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428612'`

**Comment by jsiemek** [comment]
Have during install add wrong entry into resources:

It should be:

/hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428612

It adds:

/hacsfiles/light-entity-card/null?hacstag=168744428612

**Comment by giovanni247000** [comment]
la versione 6.1.2 non funziona più devo tornare alla versione 6.0

**Comment by giovanni247000** [comment]
an update will be released that solves the problem or I have to keep version 6.0?

**Comment by msl2424** [comment]
Simply updating to 6.1.2 just now appears to have fixed it for me.

**Comment by sonar98** [comment]
6.1.2 does not fix it for me

**Comment by ljmerza** [comment]
try uninstalling and reinstalling. the previous bug may have left HACS in a bad state

**Comment by pex81** [comment]
I continue to have the same problem with 6.1.2, I have tried removing and replacing several times.
I now have 6.1.0

**Comment by budswarez** [comment]
> Have during install add wrong entry into resources:
> 
> It should be:
> 
> /hacsfiles/light-entity-card/light-entity-card.js?hacstag=168744428612
> 
> It adds:
> 
> /hacsfiles/light-entity-card/null?hacstag=168744428612

Check and remove or fix line in 
Config > Dashboard > 3 dots > ( Search entry null )

**Comment by sonar98** [comment]
Removing and reinstalling helped to solve the problem for me.

**Comment by pex81** [comment]
I've tried over and over again, but after a few uses I return to this point

<img width="555" alt="Screenshot 2024-01-06 alle 17 26 51" src="https://github.com/ljmerza/light-entity-card/assets/58252398/b6ad0d23-f6c9-4cf3-9d41-bb5c898e1ae2">
<img width="1519" alt="Screenshot 2024-01-06 alle 17 27 05" src="https://github.com/ljmerza/light-entity-card/assets/58252398/e7929b7c-c3a7-4a06-bfd3-1d990b1c4189">

only with 6.1.0 everything works normally.

**Comment by sonar98** [comment]
It stopped working again here. Got an error:
![image](https://github.com/ljmerza/light-entity-card/assets/645403/aeef0fa9-5556-40ee-8119-6fc894cb0293)

downloading again stopped the error but the other error appeared again:
![image](https://github.com/ljmerza/light-entity-card/assets/645403/061693c2-cea0-4c6a-9c18-cea57adeb9b1)

now reverting to 6.1.0 for now.
