### ISSUE TITLE
Possible to hide Effects list completely?

### ISSUE THREAD

**Issue by nappyjim** [ljmerza/light-entity-card#129]
I am using this with a WLED light strip.   I have a few presets I have made that I have made buttons for on the dashboard.  I want JUST the color wheel with this entity card, not the effects list.  I know I can make a dummy list with just 1 entry and it wouldent "do" anything, but I'd like to be hidden completely.  Thank you!

![image](https://github.com/user-attachments/assets/1a640257-b15e-4a4e-bb83-106dc278e7c2)

**Comment by DieterKoblenz** [comment]
See the documentation for this very option. 

<html>
<body>

effects_list | list/string/boolean | Optional | custom list of effects, an input_select entity, or set false to always hide
-- | -- | -- | --



</body>
</html>

**Comment by nappyjim** [comment]
> See the documentation for this very option.
> 
> effects_list | list/string/boolean | Optional | custom list of effects, an input_select entity, or set false to always hide -- | -- | -- | --

Doh!  Didn't scroll over far enough. Thank you.

**Comment by nappyjim** [comment]
Set to false.
