### ISSUE TITLE
white_value slider doesn't show

### ISSUE THREAD

**Issue by KonradLindblad** [ljmerza/light-entity-card#13]
I have a [Qubino Flush RGBW Dimmer](https://qubino.com/products/flush-rgbw-dimmer/) that doesn’t get the white_value slider to show. Setting RGB on the color picker works good but i have to use the Home Assistant dev-service and send custom JSON to the lights in order to set white_value (which works but its quite a hassle to do every time since it seems to reset to white_value: 0 every time i choose a new color).
Is it possible to force the white_value slider to show even though it probably thinks this unit doesn’t support white_value?

**Comment by ljmerza** [comment]
home assistant decides what features are supported through a `supported_features` bit. This would seem like a bug or misconfiguration on that.
