### ISSUE TITLE
Effects List dropdown

### ISSUE THREAD

**Issue by PeteCondliffe** [ljmerza/light-entity-card#18]
When using this card at the bottom of a page when clicking on the light effects dropdown it still display below even though there is no screen space available making the options really difficult to access.
![image](https://user-images.githubusercontent.com/37262524/62577206-57411900-b896-11e9-89c5-4a94d3029d14.png)
Would it be possible to make the dropdown display above when it is at the bottom of the like the one on the more info dialog.
![image](https://user-images.githubusercontent.com/37262524/62577461-ebab7b80-b896-11e9-9713-678a7f598e5e.png)

Hope this makes sense Thanks

**Comment by ljmerza** [comment]
Unforuntately, this is an issue with paper dropdown menu and wont be resolved. Home Assistant uses polymer components for the UI which have all been abandoned a year ago. They are transitioning to lit element but this wont be done any time soon. You can see the opened issue on this here https://github.com/PolymerElements/paper-dropdown-menu/issues/85
