### ISSUE TITLE
No Toggle Button in 3.0.0

### ISSUE THREAD

**Issue by eglia** [ljmerza/light-entity-card#21]
With the latest update 3.0.0, all toggle switches have disappeared from the light-entity-cards.
From the commit I can see that you switched from "paper-toggle-button" to "ha-switch", but I can't find any information about this ha-switch. 

I don't see any errors in the browser or homeassistant log.

Home Assistant: 0.99.3
Browser: multiple versions of Chrome & Firefox (Android/Windows)

**Comment by ljmerza** [comment]
This might be a v100 only thing hence the major version switch

**Comment by slinkymanbyday** [comment]
I am on v 0.100.1 and I do not have a toggle switch. Is there anything i need to change? Have restarted HA.

**Comment by eglia** [comment]
You were very quick to require 0.100, it's not event reported yet by the update sensor...

Updating to 0.100 fixed it for me, thanks for the tip.

**Comment by ljmerza** [comment]
The only change is the toggle so you can also keep the previous version. It was unfortunate the developers of HA decided to remove the old switch immediately instead of waiting a few versions. It was either have this card broken on < 0.100 or broken on >= 0.100.

**Comment by ljmerza** [comment]
> I am on v 0.100.1 and I do not have a toggle switch. Is there anything i need to change? Have restarted HA.
> 
> Edit: for clarification, this is a xiaomi bedside lamp (moonlight lamp) using the miio platform

You can try to clear cache as HA tries to save the old version of all the cards.

**Comment by slinkymanbyday** [comment]
> > I am on v 0.100.1 and I do not have a toggle switch. Is there anything i need to change? Have restarted HA.
> > Edit: for clarification, this is a xiaomi bedside lamp (moonlight lamp) using the miio platform
> 
> You can try to clear cache as HA tries to save the old version of all the cards.

Can confirm it was cache. Thanks for the suggestion

**Comment by ljmerza** [comment]
I was able to get the switch working for all versions for HA in v3.0.1
