### ISSUE TITLE
Disable more info pop-up

### ISSUE THREAD

**Issue by tomlut** [ljmerza/light-entity-card#23]
I find that when adjusting the values in the card very often (50% of the time) the more info pop-up card appears. Could we get an option to disable this?

**Comment by ljmerza** [comment]
could you take a picture of what you see? Ive never noticed a popup

**Comment by tomlut** [comment]
This was attempting to choose a lighting effect:

![IMG_0513](https://user-images.githubusercontent.com/10679300/67587501-bc265400-f79f-11e9-8685-947773b12f4d.png)

**Comment by ljmerza** [comment]
This looks like the built in HA card not this custom card.

**Comment by tomlut** [comment]
Exactly. That pops up when I'm adjusting your card (the card behind it).

**Comment by tomlut** [comment]
Ah! it's because I have it stacked in an entities card. It's the entities card generating the pop-up. Not your issue. Closing.
