### ISSUE TITLE
on/off toggle does not show up

### ISSUE THREAD

**Issue by cpomodoro** [ljmerza/light-entity-card#24]
Hi, the card (light-entity-card 3.1.0) works fine but the on/off toggle does not show up (running HA 0.102.1 on Hassio).

**Comment by ljmerza** [comment]
What type of entity is this? Did you just update HA? I know around version 100 they removed the old toggle element and added a new one

**Comment by ljmerza** [comment]
is this still an issue?

**Comment by cpomodoro** [comment]
Hi, no it is not. But I'm not sure how and when it fixed.
Thankyou anyway for your support.
Corrado

Il mar 7 gen 2020, 00:41 Leonardo Merza <notifications@github.com> ha
scritto:
