### ISSUE TITLE
HACS doesnt add light-entity-card.js.map

### ISSUE THREAD

**Issue by jaburges** [ljmerza/light-entity-card#29]
When installing through HACS, only `light-entity-card.js` is installed.

This results in the following error in HA:
```Tried to serve up '/config/www/community/light-entity-card/light-entity-card.js.map' but it does not exist```

Manually adding the file from the Github repo solves the issue. Not sure if the issue is on your side or HACS side, but thought i'd mention it.
HTH

**Comment by ljmerza** [comment]
yep looks like i still include map files in prod build. I'll take that out thanks!
