### ISSUE TITLE
Add effect dropdown

### ISSUE THREAD

**Issue by firstof9** [ljmerza/light-entity-card#3]
Would love to see the effect drop down tied to an input_select entity.

**Comment by ljmerza** [comment]
can you give an example of a use case for `input_select` with this card? I've never used that entity type before.

**Comment by firstof9** [comment]
I have an ```input_select``` setup with a list of effects I've programmed into an LED strip.

**Comment by aidbish** [comment]
isnt the effect list already in the card

**Comment by firstof9** [comment]
@aidbish no

**Comment by ljmerza** [comment]
I added this functionality in 1.3.0. See readme for details. Let me know if you have any issues thanks!
