### ISSUE TITLE
HACS adds incorrect path to lovelace config

### ISSUE THREAD

**Issue by sharpsounds** [ljmerza/light-entity-card#32]
HACS adds 
```
  - type: module
    url: /hacsfiles/light-entity-card/dist/light-entity-card.js
```
when it should be adding
```
  - type: module
    url: /hacsfiles/light-entity-card/light-entity-card.js
```

**Comment by ljmerza** [comment]
Does this still happen in the latest version of have? I know they recently fixed an import bug

**Comment by ljmerza** [comment]
HACS is having issues on their end with proper importing. Looks like they released another fix today but if this still happens after upgrading, open an issue with them.
