### ISSUE TITLE
Toggle button alignment inconsistent

### ISSUE THREAD

**Issue by wltng** [ljmerza/light-entity-card#36]
I'm using the card with a Philips Living Colors Gen1, and it works very well.
I only have one small issue:
The alignment of the toggle button doesn't match other HA toggle buttons
Is there anything that can be done about this?

![image](https://user-images.githubusercontent.com/61619985/82685197-19aa5280-9c54-11ea-8f55-3ef8c36f5d16.png)

Thanks!

**Comment by ljmerza** [comment]
should be fixed in v3.2.4

**Comment by wltng** [comment]
It has been indeed!
Thanks for your quick response.
