### ISSUE TITLE
color wheel not displaying

### ISSUE THREAD

**Issue by drivin** [ljmerza/light-entity-card#38]
I use deconz to integrate my Zigbee lamps. Deconz creates groups for individual rooms. The groups can contain different lamps. From simple white to RGBWW. 
If I use light-entity-row, I can use e.g. the colorpicker for the group.
Unfortunately this does not seem to work with light-entity-card, does it?

A deconz group has the following attributes:
effect_list:
  - colorloop
is_deconz_group: true
all_on: false
friendly_name: Living room
supported_features: 45

**Comment by ljmerza** [comment]
home assistant uses bit operations to handle supported features. The color wheel is 16 so if you do bit wise math `45 & 16 = 0` which means home assistant is telling the card that colors are not supported on this entity. If you feel like this is in error, you'd have to open an issue there so the supported_features value includes colors.

**Comment by drivin** [comment]
Thank you for your answer.
And yes, I think it is a bug. Light group integration would do this: "The supported features of all lights will be added together. For example, if you have one RGB light in a group of otherwise brightness-only lights, the light group will be shown with a color picker."

So I will remove the deconz groups and use light.group.
