### ISSUE TITLE
Option to remove entity state toggle

### ISSUE THREAD

**Issue by drivin** [ljmerza/light-entity-card#39]
I would appreciate it very much if there was a possibility to remove the toggle button. 

![Bildschirmfoto von 2020-06-04 19-04-49](https://user-images.githubusercontent.com/397867/83789195-ac0c1680-a696-11ea-9e72-0e27870bdbf4.png)

**Comment by ljmerza** [comment]
added ability to hide entire header in v4.1.0 via the `hide_header` option
