### ISSUE TITLE
Feature request always show even when off

### ISSUE THREAD

**Issue by IIIdefconIII** [ljmerza/light-entity-card#4]
Is it possible to always show the card, when i turn off the light the card looses the options, i would like to always have it opend

**Comment by IIIdefconIII** [comment]
Or possible to show the light.hyperion when the switch is turned off would be sick aswell, not sure if this is possible

**Comment by ljmerza** [comment]
ok I added this feature into v1.2.0

**Comment by IIIdefconIII** [comment]
Thanks for the quick fix, no problems for now and working as expect
