### ISSUE TITLE
ha-group with two lights - generates useless second card 

### ISSUE THREAD

**Issue by lVincentPl** [ljmerza/light-entity-card#40]
I have a group in hass.io with two RGB lights and wanted to use the light entity card to control them at the same time.
But somehow two cards are generated.
Both Cards do the same but only the first one displays the correct states.
There should be an option to hide the second card (or is there?) because the first one already has all the functionality.

![image](https://user-images.githubusercontent.com/36577908/85202083-3d6cc100-b304-11ea-91a8-dd2672399610.png)

![image](https://user-images.githubusercontent.com/36577908/85202091-4d84a080-b304-11ea-9080-10359fabf4d0.png)

**Comment by bcmitri** [comment]
I'm also experiencing this.  It's also worth noting that this issue has only surfaced recently.  I've had this plugin in my Lovelace view for quite some time and it was never an issue before.

**Comment by bcmitri** [comment]
Unfortunately, I've had to move to another plugin in order to meet my requirements.  If there is a fix to this, however, I will happily switch back.

**Comment by ljmerza** [comment]
the card will split up entities in a group by default so you can control each entity within the group individually. The names are the same because you overwrote them. I've added support to consolidate group entities via the `consolidate_entities` option in v4.0.0

**Comment by lVincentPl** [comment]
Doesn't seem to work.
![image](https://user-images.githubusercontent.com/36577908/86392924-832e6f80-bc9c-11ea-94bf-0d6921b6f1ba.png)

**Comment by bcmitri** [comment]
Worked for me.

**Comment by lVincentPl** [comment]
What type of entity do you have?

**Comment by bcmitri** [comment]
It's a light group.

**Comment by lVincentPl** [comment]
I have two RGB lights

![image](https://user-images.githubusercontent.com/36577908/86393567-8b3adf00-bc9d-11ea-9864-9d27391e2792.png)

**Comment by bcmitri** [comment]
Did you clear your cache and refresh the page?

**Comment by lVincentPl** [comment]
I reloaded with pressing the shift key.

Console outputs:   LIGHT-ENTITY-CARD     Version 4.0.0
