### ISSUE TITLE
Group - true / Consolidate entities - true / false both result in list of entities displayed in lovelace of the custom light group.

### ISSUE THREAD

**Issue by VarenDerpsAround** [ljmerza/light-entity-card#42]
I recently updated to the most recent version, seems to me it's gone a bit awry. 

I came back to my light love lace dashboard hammered with a light card of every light in my house.

Seems that the consolidate entities / group variable is not working as expected, and it results in my custom light group to display every light entity in the group.

How this was achieved when the group itself is set in home assistant in the config, it should have just displayed that group, not the entire list of lights in the group, iiuc?

Anything I can do to help?

**Comment by leafshore** [comment]
> I recently updated to the most recent version, seems to me it's gone a bit awry.
> 
> I came back to my light love lace dashboard hammered with a light card of every light in my house.
> 
> Seems that the consolidate entities / group variable is not working as expected, and it results in my custom light group to display every light entity in the group.
> 
> How this was achieved when the group itself is set in home assistant in the config, it should have just displayed that group, not the entire list of lights in the group, iiuc?
> 
> Anything I can do to help?

Same Issue, updated to latest light-entity-card AND HA, light-entity-card shows all entities as individual lights in the light-group specified in config.

**Comment by cyber-arche** [comment]
> I recently updated to the most recent version, seems to me it's gone a bit awry.
> 
> I came back to my light love lace dashboard hammered with a light card of every light in my house.
> 
> Seems that the consolidate entities / group variable is not working as expected, and it results in my custom light group to display every light entity in the group.
> 
> How this was achieved when the group itself is set in home assistant in the config, it should have just displayed that group, not the entire list of lights in the group, iiuc?
> 
> Anything I can do to help?

I too am having the same issue, I had to revert back .

**Comment by ljmerza** [comment]
ok fixed in v4.1.1
