### ISSUE TITLE
"Consolidate Entities" creates promblem with "Persist Features"

### ISSUE THREAD

**Issue by lVincentPl** [ljmerza/light-entity-card#43]
If "Consolidate Entities" is active, the card only contains the Header Line and no additional feature.

![image](https://user-images.githubusercontent.com/36577908/87836842-c63e3480-c891-11ea-8ad6-b9467d6b45bb.png)

![image](https://user-images.githubusercontent.com/36577908/87836824-ab6bc000-c891-11ea-8413-e318c6496d15.png)

**Comment by ljmerza** [comment]
yes sorry, with covid, i dont have as much free time as i did before so ive neglected my HA cards but once things setting down i do plan on cleaning everything up

**Comment by lVincentPl** [comment]
Thank you, the  group light platform works for me.
