### ISSUE TITLE
Custom element doesn't exist: light-entity-card.

### ISSUE THREAD

**Issue by dualbios** [ljmerza/light-entity-card#44]
Lovelace display red 'Custom element doesn't exist: light-entity-card.' 

the resources added to Lovelace config
```
 resources:
  - url: /www/light-entity-card/light-entity-card.js
    type: js
```

the item added to page:
```
- type: custom:light-entity-card
            entity: light.kitchen_strip
```

there is error in browser console

``chunk.55cfcfe8bf5cea239c42.js:1 GET http://xxx:8123/www/light-entity-card/light-entity-card.js net::ERR_ABORTED 404 (Not Found)
``

Home Assistant Core 0.113.3
HACS 1.3.3

**Comment by ljmerza** [comment]
`www` doesnt look like the correct url apth. I would remove the card and install through HACS

**Comment by dualbios** [comment]
HACS does not add the resources to Lovelace in YAML mode
I added it manually.
the HACS is installed into 'custom_components' folder and 'light-entity-card' is installed 'www\community'
what is the root folder to make a relative resource path?

**Comment by czm97176** [comment]
Hi, i was facing the same issue. enter path as following

/local/community/light-entity-card/light-entity-card.js

**Comment by laziukiewicz** [comment]
When installing via HACS, according to docs you should actually be pointing to `hacsfiles` folder so the full resource in lovelace is

```
    url: /hacsfiles/light-entity-card/light-entity-card.js
    type: module
```
This setup works for me (they've changed it in one of the recent HACS updates).

**Comment by janneHalttu** [comment]
I just intalled version 4.5 and when entering lovelace yaml configuration i get this error

**Comment by jompa68** [comment]
I have the same eror in my HA setup. Error 404, cannot be found in folder.
Other cards installed with HACS does not give this error.
