### ISSUE TITLE
Lovelace card header description not updating

### ISSUE THREAD

**Issue by FdDiscoming** [ljmerza/light-entity-card#51]
Header description in my lovelace card for light entity is not changing the default value.

**Comment by stewmanji** [comment]
I ran into this too. @FdDiscoming to work-around this issue, add `consolidate_entities: true` to your configuration. 

@ljmerza I noticed you don't have a CONTRIBUTING.MD so I didn't submit a pull-request directly. Looks like a quick fix for this one. The order here is incorrect and needs to put `this.config.header` first (not last): https://github.com/ljmerza/light-entity-card/blob/ed1d69b6fba6bb7b64f4827ed8bc1b3c8c7f7000/src/index.js#L246

**Comment by FdDiscoming** [comment]
@stewmanji it has been solved, thank you!

**Comment by ljmerza** [comment]
use `consolidate_entities: true` to use one header. I can't switch that line around because if you use a group entity then each entity header would be the same.
