### ISSUE TITLE
Consilidation of  lights group breaks the card

### ISSUE THREAD

**Issue by mx4k** [ljmerza/light-entity-card#60]
Hi, this happens to me, when I click on consilidation:

https://i.imgur.com/wjqMLEJ.mp4

This is my lights group:

> lights_buro:
    name: Büro
    entities:
        - light.buro_schreibtisch
        - light.buro_wand

**Comment by Buktahula** [comment]
Same here

**Comment by ljmerza** [comment]
let's track this issue here https://github.com/ljmerza/light-entity-card/issues/64
