### ISSUE TITLE
Custom element doesn't exist: light-entity-card

### ISSUE THREAD

**Issue by viciovb** [ljmerza/light-entity-card#61]
On Home Assistant android app the component doesn't work and returns the error:

Custom element doesn't exist: light-entity-card

**Comment by jasongabler** [comment]
I am experiencing the same error.  The card type shows up just fine in HACS:

![image](https://user-images.githubusercontent.com/1828132/116804155-6ee01c80-aad1-11eb-9660-5b445f175505.png)

But when I try to use it, the card is not available in the Lovelace configurator. As a last resort I follow the docs on this repo to edit the type manually and I see

![image](https://user-images.githubusercontent.com/1828132/116804341-da76b980-aad2-11eb-9509-d233cf8ac0eb.png)

**Comment by ljmerza** [comment]
this card works for a number of people. if you're still seeing this issue, try on the home assistant help forum. link is in readme
