### ISSUE TITLE
custom ligth entity card and core 5

### ISSUE THREAD

**Issue by lubitcasa** [ljmerza/light-entity-card#62]
Hello.
Since the last update core 5 and 5.1 the color wheel does not work for me.
in 4.6 everything is correct.
Is there any change to make?

**Comment by firstdominator** [comment]
Same here, I use to have a group light that showed me the color wheel on the frontend. Not there anymore...

Thanks!

**Comment by Wim-N** [comment]
Also the dimmer slider does not show, only the switch will show

**Comment by criddell94** [comment]
+1 for having the same issue with the color wheel.

**Comment by tipetii** [comment]
Since core 5.1 dimmer slider doesn't exist with grouped lights

**Comment by Buktahula** [comment]
Same issues , color wheel and slider only works if "consolidate_entities:false" and "displayType: slider"

**Comment by tchesket** [comment]
Same issue here

**Comment by lubitcasa** [comment]
hi, i still have the same problem.
core 6.2 and still not working.
install outside of HACS.
manual installation but it doesn't work either.

**Comment by lubitcasa** [comment]
it works now!!
with the last update it was solved.
thank you ljmerza
