### ISSUE TITLE
Light Entity Card doesn't show features

### ISSUE THREAD

**Issue by fenderle** [ljmerza/light-entity-card#63]
For some integrations (in this example Shelly) the card doesn't show the features of the device, like eg. the brightness slider. I realized the Shelly integration doesn't set the supported_features attribute correctly (its always 0) and I raised an issue there.

However the dev over at Homeassistant states that supported_features is being deprecated ([see here](https://github.com/home-assistant/core/issues/50698))

Currently I can only turn the lights on and off, but not dim them, etc. Would it be possible to add a flag which just shows all features which are enabled for the entity in the card?

**Comment by pmfernandes** [comment]
I'm also having the same problem with Tasmota flashed RGD led strip.

**Comment by fenderle** [comment]
Same happens with the Elgato Key Light integration

**Comment by LegionX-Code** [comment]
Hello,
@fenderle, @pmfernandes 

You said you cannot see the feature sliders? for brightness/W ect?

Just check something for me here:

- head into HA "lovelace",
- then select "developer tools"
- then select "states tab" 
- then find the entity your looking (what ever its ID or friendly name)
- then click on it, scroll back up to top of tab, you should see "State attributes (YAML, optional)"
- Look for "supported_features" & check it is set to: 145

- Can you see slider now? it may provide more info than you need right now, but lets start here first.

**Comment by LegionX-Code** [comment]
@fenderle @pmfernandes 
I'll assume you have the card configured correctly for this device as you said it was previously working, Edit UI, Edit Card, selected the features you require.

So were on the same page,
The user input sends Command but light updates the  State - not user updates state.

Is your light (entity) reporting it current "state" to HA?  
Reporting separately "(ON/OFF)", "brightness", "hs", color mode,  in the correct format? 

If not, consider this:

(a) If your device is not reporting it's current "state" back to HA, the card will close as it thinks the entity (light) is MIA.

1. HA sends "command" to light.
2. Light receives .cmd, then turns on
3. Light reports back to HA its current "state". 
4. HA Entity (light) says, ok I've received an "state" update
5. I'll update the card to "ON".   or If a valid brightness was received it would update the slider. 

Even thou you turned it on, it still requires confirmation. If it was updated from another source it would update the "state" and adjust the slider or color wheel to suit.

So if the card is not holding open after you send (1).cmd, then see if you can see how the device is reporting it current state (3) back to HA.

The card is closing as it doesn't know the "state" of the light, after sending the .cmd, so it assumes it is  MIA or Disconnected (closing the card out of sight until it receives a current state back from the light).  

As soon as the light reports to HA it's "State" 1.ON/OFF, 2.Brightness, 3 hs, 4.RGBW ect, the card will open all the other features you mentioned.
---
or
 
(b) Have you tried ticking "Persist Features" on the card, this forces the card to stay open even if no current  "state" is returned from the light.  

If this option gets you out of trouble there is a sync issue..  if you update the light from another device it will not update it current "state" to HA - so the light might be off, but the card says it on.

**Comment by fenderle** [comment]
The lights work perfectly well with the standard HomeAssistant light card. According to an issue I opened over at the HomeAssistant Github they move away from the supported_features attribute with more and more integrations ditching support for it. So please move Light Entity Card towards light modes.

https://developers.home-assistant.io/docs/core/entity/light/#support-feature lists almost all of them as deprecated (which also means they are not guaranteed to be supported)

https://developers.home-assistant.io/docs/core/entity/light/#color-modes is the new way to go I guess

**Comment by enuzzo** [comment]
Same issue here.
**HA:** core-2021.7.3
**Card Version:** 4.4.0 
**Lights:** WLED + Hyperion Project - For both, the color wheel has disappeared.

**Comment by Ellipsiss** [comment]
Same again here
HA: core-2021.7.3
Card Version: 4.4.0
Lights: Athom Tasmota bulbs running 9.5.0 with Tasmota integration working / installed.

**Comment by ljmerza** [comment]
try v4.2.3

**Comment by Bieniu82** [comment]
> try v4.2.3

color wheel still missing with cd1c6db

**Comment by ljmerza** [comment]
> > try v4.2.3
> 
> color wheel still missing with cd1c6db

Paste all your entity values and config

**Comment by Bieniu82** [comment]
> Paste all your entity values and config

core-2021.7.3
lights: WLED
Card Version: 4.4.0 / master (cd1c6db)

lovelace config:

    cards:
      - type: vertical-stack
        cards:
          - entity: light.wled
            type: 'custom:light-entity-card'  
            color_picker: true
            persist_features: true
            effects_list: true
          - entities:
            - input_number.ledspeed
            - input_number.ledintensity
            type: entities

**Comment by ljmerza** [comment]
And your entity attributes?

**Comment by Bieniu82** [comment]
effect_list:
  - Android
  - Aurora
  - Blends
  - Blink
  - Blink Rainbow
  - Bouncing Balls
  - Bpm
  - Breathe
  - Candle
  - Candle Multi
  - Candy Cane
  - Chase
  - Chase Flash
  - Chase Flash Rnd
  - Chase Rainbow
  - Chase Random
  - Chunchun
  - Circus
  - Colorful
  - Colorloop
  - Colortwinkles
  - Colorwaves
  - Dancing Shadows
  - Dissolve
  - Dissolve Rnd
  - Drip
  - Dynamic
  - Dynamic Smooth
  - Fade
  - Fill Noise
  - Fire 2012
  - Fire Flicker
  - Fireworks
  - Fireworks 1D
  - Fireworks Starburst
  - Flow
  - Glitter
  - Gradient
  - Halloween
  - Halloween Eyes
  - Heartbeat
  - ICU
  - Juggle
  - Lake
  - Lighthouse
  - Lightning
  - Loading
  - Meteor
  - Meteor Smooth
  - Multi Comet
  - Noise 1
  - Noise 2
  - Noise 3
  - Noise 4
  - Noise Pal
  - Oscillate
  - Pacifica
  - Palette
  - Percent
  - Phased
  - Phased Noise
  - Plasma
  - Police
  - Police All
  - Popcorn
  - Pride 2015
  - Railway
  - Rain
  - Rainbow
  - Rainbow Runner
  - Random Colors
  - Ripple
  - Ripple Rainbow
  - Running
  - Running 2
  - Saw
  - Scan
  - Scan Dual
  - Scanner
  - Scanner Dual
  - Sine
  - Sinelon
  - Sinelon Dual
  - Sinelon Rainbow
  - Solid
  - Solid Glitter
  - Solid Pattern
  - Solid Pattern Tri
  - Sparkle
  - Sparkle Dark
  - Sparkle+
  - Spots
  - Spots Fade
  - Stream
  - Stream 2
  - Strobe
  - Strobe Mega
  - Strobe Rainbow
  - Sunrise
  - Sweep
  - Sweep Random
  - TV Simulator
  - Tetrix
  - Theater
  - Theater Rainbow
  - Traffic Light
  - Tri Chase
  - Tri Fade
  - Tri Wipe
  - Twinkle
  - Twinklecat
  - Twinklefox
  - Twinkleup
  - Two Areas
  - Two Dots
  - Washing Machine
  - Wipe
  - Wipe Random
supported_color_modes:
  - rgb
color_mode: rgb
brightness: 127
hs_color:
  - 75.094
  - 62.353
rgb_color:
  - 215
  - 255
  - 96
xy_color:
  - 0.372
  - 0.516
effect: Solid
intensity: 192
palette: Default
playlist: null
reverse: false
speed: 192
friendly_name: WLED
icon: mdi:led-strip-variant
supported_features: 36

**Comment by fribse** [comment]
I don't see the colorwheel either for my WLED instances at the moment :-(

**Comment by ljmerza** [comment]
> supported_features: 36

according to this, your entity does not support the color wheel. Color wheel is 16 so `36 & 16 = 0`. I would ask on the HA forums about htis if you think it's incorrect.




> I don't see the colorwheel either for my WLED instances at the moment :-(

I understand your frustration, but this is not the place to complain - take that to the HA forums, this is GitHub. Add your config and entity values to be constructive in finding this issue out. If not, I'll lock this issue.

**Comment by Bieniu82** [comment]
> according to this, your entity does not support the color wheel. Color wheel is 16 so `36 & 16 = 0`. I would ask on the HA forums about this if you think it's incorrect

will raise it there; for now decided to change ha back to core-21.6.6, as other stuff e.g. sms integration seems to be broken tin the newest one; with ha core-21.6.6 the color wheel is back (with both 4.4.0 as well as newest master cd1c6db)

**Comment by Lennart99** [comment]
Brightness slider is not being shown for lights that are off even though Persist Features is turned on, Brightness slider is shown when light is turned on.

I am using Home Assistant version 2021.7.4, HACS version 1.13.2 and version 4.4.0 of this card.

![image](https://user-images.githubusercontent.com/23156309/125118872-987c7c00-e0f0-11eb-9f2f-535c0c27e393.png)

**Comment by ljmerza** [comment]
paste your entity attributes

**Comment by Lennart99** [comment]
```min_mireds: 140
max_mireds: 650
supported_color_modes:
  - color_temp
is_deconz_group: false
friendly_name: Lamp TV
supported_features: 40
```

**Comment by ljmerza** [comment]
latest is v4.4.2

**Comment by Lennart99** [comment]
I can't find that version on HACS, unfortunately
I also tried to install master, but that does not seem to work either

**Comment by Lennart99** [comment]
Fixed for me with 4.4.4 
Thank you

**Comment by fenderle** [comment]
Works for me with 4.4.4. Thank you for your work. Closing this issue.

**Comment by twelve-cgn** [comment]
> Brightness slider is not being shown for lights that are off even though Persist Features is turned on, Brightness slider is shown when light is turned on.
> 
> I am using Home Assistant version 2021.7.4, HACS version 1.13.2 and version 4.4.0 of this card.
> 
> ![image](https://user-images.githubusercontent.com/23156309/125118872-987c7c00-e0f0-11eb-9f2f-535c0c27e393.png)

For me it still exists on 4.4.4 on HA 2021.8.1 and HACS 1.13.2
