### ISSUE TITLE
Color picker on tasmota v8.2 RGB lamp not showing

### ISSUE THREAD

**Issue by maximka87** [ljmerza/light-entity-card#66]
I have a tasmota led strip L1 which is running v8.2 and suddenly stopped showing the color picker. I have tried putting previous versions, uninstalling and reinstalling but nothing. The default component of the HA is working, so it's not like its not publishing it's colours. 
Another component i have (shelly bulb) is working just fine.
Do i need to upgrade the L1 contoller to later tasmota version?

Thanks,

![entity light](https://user-images.githubusercontent.com/63750584/124203411-56967900-dae5-11eb-9a77-07e1d6b97f08.JPG)

**Comment by ljmerza** [comment]
this has to do with how HA reports the supoprted features of an entity. Make sure your `supported_features` attribute is correct.

**Comment by maximka87** [comment]
Can you please explain a little better how to do that? I'm searching but i'm a little lost with different things. This entity is autodiscoverable from the tasmote feature. Should i now write it manually on the configuration.yaml and put some supported_fetaures with some number next to it?

Thanks,
Maxim

**Comment by lubitcasa** [comment]
> I have a tasmota led strip L1 which is running v8.2 and suddenly stopped showing the color picker. I have tried putting previous versions, uninstalling and reinstalling but nothing. The default component of the HA is working, so it's not like its not publishing it's colours.
> Another component i have (shelly bulb) is working just fine.
> Do i need to upgrade the L1 contoller to later tasmota version?
> 
> Thanks,
> 
> ![entity light](https://user-images.githubusercontent.com/63750584/124203411-56967900-dae5-11eb-9a77-07e1d6b97f08.JPG)

the same here with a rgb lamp and tasmota 9.5.
if I change supported_features: 17 the color sleep appears .....
but when I touch on it it disappears

**Comment by ljmerza** [comment]
> Can you please explain a little better how to do that? I'm searching but i'm a little lost with different things. This entity is autodiscoverable from the tasmote feature. Should i now write it manually on the configuration.yaml and put some supported_fetaures with some number next to it?
> 
> Thanks,
> Maxim

what is the vslue of `supported_features` atttribute?

**Comment by lubitcasa** [comment]
> > Can you please explain a little better how to do that? I'm searching but i'm a little lost with different things. This entity is autodiscoverable from the tasmote feature. Should i now write it manually on the configuration.yaml and put some supported_fetaures with some number next to it?
> > Thanks,
> > Maxim
> 
> what is the value of `supported_features` atttribute? This value will need to return 16 on `16 & supported_features`

supported_features: 36 ....... is the value of my entities in tasmota.
if I put this on the card it doesn't work.
If I go to the developer tool, I select the entity Tasmota light and change the value from 36 to 17 ....... the card appears correctly ..... brightness .... color wheel .... etc.
it stays like this until I act on the entity (on ... color ... brightness) ..... returns to its value 36 and disappears in HA

**Comment by maximka87** [comment]
> > Can you please explain a little better how to do that? I'm searching but i'm a little lost with different things. This entity is autodiscoverable from the tasmote feature. Should i now write it manually on the configuration.yaml and put some supported_fetaures with some number next to it?
> > Thanks,
> > Maxim
> 
> what is the value of `supported_features` atttribute? This value will need to return 16 on `16 & supported_features`

Hello ljmerza,

Supported_features needs to be activated through the configuration.yaml is that correct? 
And then on the customize.yaml i need to put the correct values of the features.

Thanks

**Comment by lubitcasa** [comment]
> > > Can you please explain a little better how to do that? I'm searching but i'm a little lost with different things. This entity is autodiscoverable from the tasmote feature. Should i now write it manually on the configuration.yaml and put some supported_fetaures with some number next to it?
> > > Thanks,
> > > Maxim
> > 
> > 
> > what is the value of `supported_features` atttribute? This value will need to return 16 on `16 & supported_features`
> 
> Hello ljmerza,
> 
> Supported_features needs to be activated through the configuration.yaml is that correct?
> And then on the customize.yaml i need to put the correct values of the features.
> 
> Thanks

no, i use it with tasmota integration (setoption19 0)
in yaml I do not put anything (previously if I use it from yaml)

**Comment by ljmerza** [comment]
home assistant generates the `supported_features` attribute itself so you will not be able to set it manually. If you believe home assistant is not returning a correct `supported_features` value to support color wheel, I would open an issue with home assistant (or the custom integration's maintainer isf this is custom) as this would be an issue on that end.

**Comment by ljmerza** [comment]
try v4.4.0
