### ISSUE TITLE
color wheel not showing up on the card having upgraded ha to 21.7

### ISSUE THREAD

**Issue by Bieniu82** [ljmerza/light-entity-card#67]

**Comment by SquaredCircleHunter** [comment]
Please see my comment in https://github.com/ljmerza/light-entity-card/issues/65

**Comment by ljmerza** [comment]
try 4.4.1

**Comment by Bieniu82** [comment]
4.4.0 - ha card ok, lovelace card NOT ok
4.4.1 - ha card NOT ok, lovelace card NOT
master (4.4.2) - ha card NOT ok, lovelace card NOT ok

**Comment by SquaredCircleHunter** [comment]
I just tested 4.2.2, works again!

**Comment by zither911** [comment]
Having the same issues after last HA update. Tried reinstalling the card but the color temp and wheel wont show

**Comment by ljmerza** [comment]
trafck here https://github.com/ljmerza/light-entity-card/issues/63
