### ISSUE TITLE
Brightness not being shown for lights that are off even though Persist Features is turned on

### ISSUE THREAD

**Issue by Lennart99** [ljmerza/light-entity-card#68]
Using Home Assistant version 2021.7.1, HACS version 1.13.2 and version 4.4.0 of this card

![image](https://user-images.githubusercontent.com/23156309/125118872-987c7c00-e0f0-11eb-9f2f-535c0c27e393.png)

**Comment by ljmerza** [comment]
track here https://github.com/ljmerza/light-entity-card/issues/63
