### ISSUE TITLE
Feature Request - Grouped Lights to not turn on if values are modified

### ISSUE THREAD

**Issue by Tar-rask** [ljmerza/light-entity-card#69]
To explain the reasoning, I have grouped lights card, though during the night I would manually turn two lights off, with another two left on. However in the grouped card, if you then modify any values (colour / brightness / temp) it turns on the the lights when are switched off.

So would be a nice if there was a option to no turn on the lights if a value get modified.

**Comment by ljmerza** [comment]
thats how home assistant works on light groups. you can try asking on their fourms but i dont think they would change it.
