### ISSUE TITLE
Custom element doesn't exist: light-entity-card #61

### ISSUE THREAD

**Issue by qosmio** [ljmerza/light-entity-card#71]
Frontend version: **20210729.0 - latest**
Home Assistant Version: **core-2021.7.4**
Light-entity-card: **4.4.2**
Using HACS to manage updating

Reopening #61 as upgrading to 4.4.2 causes this error to return both using web version and iOS integrated version of HA. Cleared frontend cache  As well as clean browser session in private mode. 

Forcing downgrade to 4.4.0 is the only thing that resolves the issue.

**Comment by ischorr** [comment]
Same here, after upgrade to latest HA and 4.4.2 at pretty much the same time.

**Comment by Qpernicus** [comment]
Just updated, same problem.

**Comment by stephenjamieson** [comment]
Yep, same.

**Comment by fribse** [comment]
One more to the choir, darned.

**Comment by Toolhead** [comment]
Yep, me too.

**Comment by enuzzo** [comment]
**Problem:** light-entity-card not found
**Actions:** performed reinstall - uninstall - install
**Inspection:** by looking in */www/community/light-entity-card, only "babel.config.js" is there. Other files are missing and also the folder "dist" with "light-entity-card.js" is missing.


**Solution:** downloaded all the files, put them in place (still not working) > went to Configuration > LoveLace Dashboards > Resources > Changed the path for the light-entity-card.js to: "/hacsfiles/light-entity-card/dist/light-entity-card.js" ...and there you go

**Notes:** first of all super thanks to the author for this great addon! - second: remember to update the instructions for manual install of the JS, as adding resources manually in the lovelace config is no more supported - the right way is going to: Configuration > LoveLace Dashboards > Resources - and add them via GUI.

**Comment by crgreenwood** [comment]
I'm seeing exactly the same issue as @enuzzo, I've downgraded to 4.4.0 for now.

**Comment by stephenjamieson** [comment]
No change in 4.4.4 that was just released - @ljmerza

**Comment by ljmerza** [comment]
im using the latest HA and latest card version and everything looks good here on latest chrome and firefox. Are there any errors in the console? the console does say light entity cared v 4.4.4 right?

**Comment by stephenjamieson** [comment]
Can I assume by console you’re referring to something with the hassio installation?  Maybe the common theme here is that we’re all using the manual install. 

The input from @enuzzo is spot on

> Inspection: by looking in */www/community/light-entity-card, only "babel.config.js" is there. Other files are missing and also the folder "dist" with "light-entity-card.js" is missing.

I am seeing the same. This is with installation through hacs which worked fine previously.

**Comment by crgreenwood** [comment]
I have exactly the same issue with 4.4.4. I'm installing via HACS. As soon as I update to 4.4.2 or 4.4.4, /www/community/light-entity-card contains babel.config.js & babel.config.gz. When I use HACS to reinstall 4.4.0 I have light-entity-card.js & light-entity-card.js.gz and it's working again.

**Comment by ljmerza** [comment]
> Can I assume by console you’re referring to something with the hassio installation? Maybe the common theme here is that we’re all using the manual install.

im talking about the developer console in the browser.


> The input from @enuzzo is spot on
> 
> > Inspection: by looking in */www/community/light-entity-card, only "babel.config.js" is there. Other files are missing and also the folder "dist" with "light-entity-card.js" is missing.
> 
> I am seeing the same. This is with installation through hacs which worked fine previously.

This would be a problem in the installation as the `light-entity-card.js` file in the `dist` folder is the only file you need

**Comment by Lennart99** [comment]
@ljmerza it looks like light-entity-card.js has not been added to the recent releases, it is there for 4.4.0, but not for 4.4.2 and 4.4.4

**Comment by ljmerza** [comment]
added

**Comment by Lennart99** [comment]
Fixed for me after the file was added :+1:
