### ISSUE TITLE
White color temp and value doesn't show after 2020.8

### ISSUE THREAD

**Issue by fribse** [ljmerza/light-entity-card#72]
HA 2020.8.4
Light entity card 4.4.4

We got the colorwheel back, and thankyou very much for the hard work on that.
But I still don't see the color temp and value for the white.
![image](https://user-images.githubusercontent.com/13660621/128668958-3cbdf713-92af-46df-80d3-9b1d0ef018af.png)
The corresponding esphome light:
![image](https://user-images.githubusercontent.com/13660621/128669004-074513fb-7aaa-40ec-839d-e199c4dd4bb5.png)

Or a wled light
![image](https://user-images.githubusercontent.com/13660621/128669257-511635e1-47dc-4d19-bb82-b1e8706f0056.png)
And the corresponding wled light:
![image](https://user-images.githubusercontent.com/13660621/128669079-dc60da57-f073-4555-94d5-0ca426ecc89d.png)

**Comment by Warmaker-be** [comment]
HASSIO: 2021.8.7
light-entity-card: 4.4.4

Same issue, different light. I have only white lights (cold & warm) and the 2 silders are not shown anymore.
![image](https://user-images.githubusercontent.com/57051668/129980523-ef5e059b-697b-4757-b1c8-929161afd717.png)
![image](https://user-images.githubusercontent.com/57051668/129980640-8fc1e951-d39b-4450-bb4a-e85256c1e263.png)

**Comment by fribse** [comment]
It seems to be a mishap between ESPHome and Home Assistant. I think they've finally settled their differences in the latest update to both HA and ESPHome, and the function is back. If I manipulate the color it switches to color, and if I manipulate the colour temperature it switches to that. In the original HA card it switches between the two modes via some buttons, but I think this is way more elegant.

**Comment by ljmerza** [comment]
Yes ive noticed a lot more breaking changes lately even on minor updates. it's the wild west when it comes to updating HA. biggest downfall of the app for sure. glad you got it sorted out.
