### ISSUE TITLE
Light selection list is hard to use, no sorting or 'typing' to find light

### ISSUE THREAD

**Issue by fribse** [ljmerza/light-entity-card#73]
Hey there

I have a small quib.

When I set up the card, and go to select the light, I can't figure out the sorting of the list, or start typing the entity name to narrow down the list.
With all the lights and switches I have, it takes quite a while to find the right one, and I often have to scroll through the list more than once to find it.

The attached images are from the selection list in the card

![image](https://user-images.githubusercontent.com/13660621/128669980-1c07a23c-c99c-4754-95a6-d855a1ffb09b.png)
![image](https://user-images.githubusercontent.com/13660621/128670028-6f095f13-24dd-428c-a382-e8f747ed741a.png)

**Comment by ljmerza** [comment]
added sorting to entities list v4.4.5. will add search at some point
