### ISSUE TITLE
Brightness & Color temperature doesn't show anymore

### ISSUE THREAD

**Issue by Warmaker-be** [ljmerza/light-entity-card#74]
HassOS : 2021.8.7
light-entity-card: 4.4.4

light entity through Deconz.

Same issue, different light. I have only white lights (cold & warm) and the 2 silders are not shown anymore. it doesn't how anymore after updating HassOS from 2021.6.6 to 2021.8.7
![image](https://user-images.githubusercontent.com/57051668/129980523-ef5e059b-697b-4757-b1c8-929161afd717.png)

standard Lovelace lights
![image](https://user-images.githubusercontent.com/57051668/129980640-8fc1e951-d39b-4450-bb4a-e85256c1e263.png)

**Comment by ljmerza** [comment]
paste the entity's attributes here please

**Comment by Warmaker-be** [comment]
@ljmerza do you mean this?
![image](https://user-images.githubusercontent.com/57051668/130089783-abe87923-0976-4fa4-b1f3-faf05857b0ca.png)

**Comment by ljmerza** [comment]
No should be in the developer tools -> states table section of HA

**Comment by ljmerza** [comment]
i couldnt reproduce using those attributes. try clearing cache on your browser

**Comment by Warmaker-be** [comment]
Thank you for the support, it worksnow .
I already tried that before. don't know what changed in between
