### ISSUE TITLE
effect list dropdown UI issues

### ISSUE THREAD

**Issue by regevbr** [ljmerza/light-entity-card#86]
Starting v5.0.0, when you open the dropdown menu in a mobile view, and the button is positioned at the top of the view like that:
![Screenshot-20220313230920-363x748](https://user-images.githubusercontent.com/5775519/158079371-7f520a40-870f-4b92-b52b-0287c17583aa.png)

The menu isn't opening properly, and causing the containing card to be "stretched" like so:

![Screenshot-20220313230932-356x768](https://user-images.githubusercontent.com/5775519/158079374-c76bd412-faab-4ec6-a100-d46277502a67.png)

**Comment by ljmerza** [comment]
thats actually what i did and it worked fine. hopefully someone else can reproduce this as well. Since this dropdown uses MWC i wonder if its a big in that library itself

**Comment by regevbr** [comment]
You know what - you are right - my bad. The issue happens to me when I put it inside another containing card
